export interface StatField {
  name: string;
  text: string;
  maxDots?: number;
  dots?: number;
  hasAdvantage?: boolean;
  advantege?: string;
}

export interface SheetHeaderFields {
  text: string;
  name: string;
  inputType?: string;
  options?: any[];
  editWarning?: string;
}

export interface SheetAttributesField {
  type: string;
  attributes: StatField[];
}

export interface SheetAbilitiesField {
  type: string;
  abilities: StatField[];
}

// Generated by https://quicktype.io

export interface TopLevel {
  defaults: Defaults;
  configs: Configs;
  users: User[];
}

export interface Configs {
  characterSheetFields: CharacterSheetFields;
  showPortraits: boolean;
}

export interface CharacterSheetFields {
  headerFieldList: HeaderFieldList[];
  attributesFieldList: AttributesFieldList[];
  abilitiesFieldList: AbilitiesFieldList[];
}

export interface AbilitiesFieldList {
  type: string;
  abilities: Ability[];
}

export interface Ability {
  name: string;
  text: string;
}

export interface AttributesFieldList {
  type: string;
  attributes: Ability[];
}

export interface HeaderFieldList {
  name: string;
  text: string;
  editWarning?: string;
  inputType?: string;
  options?: Option[];
}

export interface Option {
  text: string;
  value: number | string;
}

export interface Defaults {
  clans: DefaultsClan[];
}

export interface DefaultsClan {
  name: string;
  disciplines: string[];
}

export interface User {
  id: string;
  username: string;
  lastSelectedChronicle: string;
  chronicles: Chronicle[];
}

export interface Chronicle {
  id: string;
  name: string;
  lastSelectedCharacter: null | string;
  clans: ChronicleClan[];
}

export interface ChronicleClan {
  name: string;
  characters: Character[];
}

export interface Character {
  id: string;
  name: string;
  clan: string;
  imageUrl: string;
  nature: string;
  demeanor: string;
  sire?: string;
  generation: number;
  concept: string;
  lastSelectedNote: null | string;
  stats: Stats;
  notes: Note[];
}

export interface Note {
  id: string;
  title: string;
  subtitle: string;
  content: string;
}

export interface Stats {
  strength?: Appearance;
  dexterity?: Appearance;
  stamina?: Appearance;
  charisma?: Appearance;
  manipulation?: Appearance;
  appearance?: Appearance;
  perception?: Appearance;
  intelligence?: Appearance;
  wits?: Appearance;
}

export interface Appearance {
  value: number;
  advantage: null | string;
}
